### ISSUE TITLE
Lint JS

### ISSUE THREAD

**Issue by tehp** [OpenPoGo/OpenPoGoBot#1]
Much of the projects JavaScript needs linting.

**Comment by MaxLeiter** [comment]
This could also be setup as a CI test in the future?

**Comment by joseph-abell** [comment]
What javascript needs linting? As far as I can tell we have json only, no more javascript.

**Comment by Reaver01** [comment]
I am working on this currently. You can assign it to me.

**Comment by meyer9** [comment]
Closing this as we now have a dedicated web repo.
