### ISSUE TITLE
Web interface overhaul

### ISSUE THREAD

**Issue by meyer9** [OpenPoGo/OpenPoGoBot#10]
We'll be overhauling the web interface.

[ ] Should use better storage method of game state
[ ] Should use AngularJS instead of jQuery

**Comment by wchill** [comment]
[ ] Should use websockets

**Comment by joseph-abell** [comment]
Do I dare ask, which version of Angular?

**Comment by wchill** [comment]
1.x?

**Comment by MaxLeiter** [comment]
I think the web interface could be its own repo, and I think angular would be overkill. I think a basic web interface is all we need (Jquery and angular aren't really comparable: one is a set of utilities the other is an entire MVW framework)

**Comment by wchill** [comment]
Yeah, no need for anything fancy. Some REST APIs, flask-socketio, and a simple enough design will probably suffice

**Comment by joseph-abell** [comment]
In terms of my side of things, I cannot stand working with angular 1.x. As soon as you go off the beaten track, and not trust in the magic they give you, everything gets messy quickly. I've had much happier times with react, although that doesn't play well with jquery either (but I'm ok with that)

**Comment by joseph-abell** [comment]
I'm happy with rest apis, will need to look into flask-socketio though.

**Comment by wchill** [comment]
I can do Flask-SocketIO, if you do the frontend part of SocketIO

**Comment by joseph-abell** [comment]
sounds good

**Comment by meyer9** [comment]
Closing this as there is now a dedicated repo for web.
