### ISSUE TITLE
web ui not working for me

### ISSUE THREAD

**Issue by captainmustard** [OpenPoGo/OpenPoGoBot#100]
![screenshot from 2016-07-27 20 38 57](https://cloud.githubusercontent.com/assets/4436461/17198785/b1ed8642-543d-11e6-9779-556c3ae65648.png)

**Comment by widnyana** [comment]
please execute `python -m SimpleHTTPServer` from `web` directory, then open `http://localhost:8000`

**Comment by wchill** [comment]
If you are on latest commit on master branch, running `python -m SimpleHTTPServer` is no longer necessary. Simply open `http://localhost:8000` after the bot has started.

**Comment by Backenkoehler** [comment]
@widnyana @wchill Bot Path and Showing Trainer just works on localhost. If you use your own local ip like 192.168. ... it doesn't work anymore. Do you have any suggestions?

JS Error:

`main.js:149 Uncaught TypeError: Cannot read property 'setOptions' of undefined`

**Comment by 1karu5** [comment]
Same error even on lokalhost here
updating web did help with the trainer stuff...but it got a lot of other issues. you cant move the map or see anything there
