### ISSUE TITLE
pgoapi not working?

### ISSUE THREAD

**Issue by captainmustard** [OpenPoGo/OpenPoGoBot#118]
After updating today when I try to start the bot I get this repeating over and over. I log in with a google account and everything was working fine before.

[2016-07-30 13:32:27] [+] Login to Pokemon Go successful.
[API] Token has expired, attempting to log back in...
ERROR:pgoapi.pgoapi:Login failed - unexpected server response!
[API] Failed to login. Waiting 15 seconds...
ERROR:pgoapi.pgoapi:Login failed - unexpected server response!
[API] Failed to login. Waiting 15 seconds...

**Comment by wchill** [comment]
Fixed in #119.
