### ISSUE TITLE
Better structure of pathing and stepping

### ISSUE THREAD

**Issue by andythorne** [OpenPoGo/OpenPoGoBot#127]
So I'm finding the bot's structure a little all over the place:
- `pokecli` invokes the `bot`
- `bot` then passes straight throught to the `stepper`
- the `stepper` gets a list of cell ids and calls the `bot` back
- which then calls `workers` when it wants
- the `walk_towards_fort_worker` then calls the `stepper` back again and we go around in circles until all the stop have been visited.

While it works, it makes modifying workers and pathing more difficult as there is worker logic in the bot and pathing logic in both the bot and the workers.

I've been working on a way to solve it, and i've come up with this:
- A `Mapper` component will handle map-only functions, like fetching cell IDs from a lat/long coord.
- All movement will be handled by a `Navigator`. The `Navigator` is responsible for choosing where the bot will go. For now, we will have a `FortNavigator` that will visit forts, but any `Navigator` can be easily created, for example something like a `WaypointNavigator` that will walk a pre-set path.
- All pathing (that is HOW you get to the point (coords) a `Navitgator` has choosen) will be done by `PathFinders`. Examples we have now would be a `GoogleDirectionsPathFinder`, which uses the google directions api, and `DirectPathFinder`, which goes directly there.
- The `Stepper` now ONLY handles moving the bot and tracking it's current and origin locations.
- `Workers` now self contained and are passed a `Cell` instance and are to work only on this `Cell`. An array of all `Workers` is kept in the `bot`

So, the flow would look more like this:
- `pokecli` invokes the `bot` ([pokecli.py#L240](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokecli.py#L240))
- `bot` requests initial cell ids from the `Mapper` ([pokemongo_bot/**init**.py#L85](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokemongo_bot/__init__.py#L85))
- `bot` invokes all `Workers` with cell ids (pre-movement workers) ([pokemongo_bot/**init**.py#L86](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokemongo_bot/__init__.py#L86))
- `bot` invokes `Navigator` with cell ids ([pokemongo_bot/**init**.py#L88](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokemongo_bot/__init__.py#L88))
- `Navigator` builds a destination and tells the `Stepper` to move there. ([pokemongo_bot/navigation/fort_navigator.py#L42-L45](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokemongo_bot/navigation/fort_navigator.py#L42-L45))
- `Stepper` will find the way there using a `PathFinder` ([pokemongo_bot/stepper.py#L54](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokemongo_bot/stepper.py#L54) -> [pokemongo_bot/navigation/path_finder/google_path_finder.py](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokemongo_bot/navigation/path_finder/google_path_finder.py))
- `Stepper` will move, 1 step at a time towards location along the `PathFinder`'s path. Each step invokes the `Workers` with the current location's cell ids. ([pokemongo_bot/stepper.py](https://github.com/andythorne/OpenPoGoBot/blob/walkers/pokemongo_bot/stepper.py))
- Jumps back to `Navigator` to choose next direction to travel.

It makes more sense to me this way, and keeps all the components de-coupled.

Any thoughts?

**Comment by wchill** [comment]
#126 is one way to get this done; the idea is that each different process that the bot needs to perform will work by triggering a series of event pipelines.

**Comment by andythorne** [comment]
#126 is a great way of getting rid of `Workers`, which I don't see as a bad thing!

I think this can still apply to navigation, however.

**Comment by wchill** [comment]
Yeah, I don't disagree with you there.

#126 has just been merged, so feel free to start filing PRs based off of that if you want to get started on this.

**Comment by wchill** [comment]
The above referenced PR removes all `Workers` except `walk_towards_fort_worker`. Some ideas on how to best refactor this as described above would be appreciated.

**Comment by andythorne** [comment]
Great work on removing the workers!

I think we can modify my original suggestion and refactor the `walk_towards_fort_worker` into a navigator:
- `pokecli` invokes the `bot`, `bot` fire any events.
- `bot` requests initial cell ids from the `Mapper`
- `bot` invokes `Navigator` with cell ids
- `Navigator` builds a destination and tells the `Stepper` to move there.
- `Stepper` will find the way there using a `PathFinder`
- `Stepper` will move, 1 step at a time towards location along the `PathFinder`'s path. Each step invokes the `bot` to process a cell (which will handle all the event firing.
- Jumps back to `Navigator` to choose next direction to travel.

Seem good?

**Comment by andythorne** [comment]
I rebased from #129 on https://github.com/andythorne/OpenPoGoBot/tree/walkers and it seems to work pretty well with a few modifications to existing event listeners:
- `spin_pokestop` now listens for nearby pokestops (within 15m) and spins them if they are off CD, rather than waiting to be told we are at a pokestop. This allows us to decouple the "i'm at a pokestop" logic in the current worker. it also allows us to follow _any_ route and spin pokestops on the way (for example. if we want to follow a set path).

**Comment by andythorne** [comment]
Seems to work well on predefined paths - it picks up all the pokestops and pokemon along the way!

**Comment by andythorne** [comment]
Done in #136
