### ISSUE TITLE
Config mode and bot behavior

### ISSUE THREAD

**Issue by 1karu5** [OpenPoGo/OpenPoGoBot#130]
### Expected Behavior

If i set mode in config to "all", i expect that the bot wont change it.
### Actual Behavior

If my bag is full, the bot changes mode to "poke" (https://github.com/OpenPoGo/OpenPoGoBot/blob/64768648983982a4981d2af28128201372b71420/pokemongo_bot/cell_workers/seen_fort_worker.py#L88) and just catches pokemon until there are no pokeballs left.
Without pokeballs it will change to "farm" (https://github.com/OpenPoGo/OpenPoGoBot/blob/69a376bbf0cec29536a8d466ce4db11949ee7d89/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L139) and the bot will only farm.
### BetterBehavior

I think it should clean the inventory as set with item_filter on full bags. And it should farm only to get a few balls if there are none and start catching pokemons after that.

**Comment by andythorne** [comment]
As far as I can see, this will be addressed and fixed in #129 as the concept of a `mode` has been removed :)

**Comment by andythorne** [comment]
Closing as #129 is merged.
