### ISSUE TITLE
Login server busy

### ISSUE THREAD

**Issue by Polarski** [OpenPoGo/OpenPoGoBot#131]
### Expected Behavior

On login i should be able play
### Actual Behavior

I get login servers busy non stop
### Steps to Reproduce

Use config.json
### Other Information

OS: Ubuntu 14.04
Git Commit:  Newest

**Comment by wchill** [comment]
If you are running the bot on a cloud provider, this is a known issue as Niantic has blocked cloud provider IPs from accessing their API.
