### ISSUE TITLE
Inventory Not Filtering/Recycling

### ISSUE THREAD

**Issue by ch333** [OpenPoGo/OpenPoGoBot#133]
### Expected Behavior

Filter items on login based on config.json file.
Recycle items from stop when item is over limit specified in config.json file.
### Actual Behavior

Not filtering or recycling
### Steps to Reproduce

Normal play
### Other Information

OS: OSX
Git Commit: Master - latest pull from 7/31/16

**Comment by wchill** [comment]
Recycle items is currently not 100% functional. PRs 129 and 132 will fix this when merged.
