### ISSUE TITLE
Bot stands still?

### ISSUE THREAD

**Issue by 1karu5** [OpenPoGo/OpenPoGoBot#140]
### Expected Behavior

Bot moving around from pokestop to pokestop
### Actual Behavior

Bot stands still and only catches pokemon since 0db7bf859f155bb922937f469bfce1187c57f767:

> [2016-08-01 01:31:56] [Transfer] No Pokemon to transfer.
> [2016-08-01 01:31:56] [Transfer] Transferred 0 Pokemon.
> [2016-08-01 01:31:56] [#]
> [2016-08-01 01:31:56] [x] Starting PokemonGo Bot....
> [2016-08-01 01:31:57] [Catch] A wild Magikarp appeared! [CP 44] [Potential 0.64]
> [2016-08-01 01:32:01] [Catch] Using Pokeball... (69 left!)
> [2016-08-01 01:32:01] [Catch] Magikarp has been caught! (CP 44, IV 0.64)
> [2016-08-01 01:32:01] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy

Then nothing else happens
Output with ec5b155d6d10047a5d06a9394012fc3017d5787f:

> [2016-08-01 01:36:21] [x] Starting PokemonGo Bot....
> [2016-08-01 01:36:21] [#] Found fort XXXXXXXXXXXXX at distance 0.01km
> [2016-08-01 01:36:21] [#] Moving closer to XXXXXXXXXXXXX
> [2016-08-01 01:36:21] [#] Walking from (XXXXXXXXXXXXX, XXXXXXXXXXXX) to (XXXXXXXX, XXXXXX) for approx. 6.00 seconds
> [2016-08-01 01:36:26] [#] Something rustles nearby!
> [2016-08-01 01:36:26] [] A Wild Staryu appeared! [CP 341] [Potential 0.69]
### Steps to Reproduce

Just start the bot
### Other Information

OS: debian
Git Commit:

**Comment by ch333** [comment]
Same problem here.  Or maybe it catches a pokemon every 10 mins (if one regenerates in the same place), but no stops and no moving.

OS: OSX
