### ISSUE TITLE
Map doesn't show bot

### ISSUE THREAD

**Issue by jonathanbalagot** [OpenPoGo/OpenPoGoBot#146]
After launching the web map, everything is populated except the bot location. Am I missing something here? I made sure to fill in the username array and API key for userdata.js

http://i.imgur.com/phXQ4ff.png

Running master - e1bd866e7297663bb236efd719a4122543a4adc5

**Comment by wchill** [comment]
Known issue, we haven't modified bot/web to talk to each other with events.

I'm working on it.

**Comment by andythorne** [comment]
Duplicate of #124
