### ISSUE TITLE
Not Transferring Caught Pokemon

### ISSUE THREAD

**Issue by ch333** [OpenPoGo/OpenPoGoBot#149]
### Expected Behavior

Transfer pokemon below set CP and IV
### Actual Behavior

Keeping all caught pokemon
### Steps to Reproduce

normal use
### Other Information

OS: OSX
Git Commit:  Latest Version

**Comment by wchill** [comment]
I assume you mean it doesn't transfer immediately after Pokemon are caught? This is expected behavior as it now only transfers when the bag is full.

**Comment by ch333** [comment]
Ok.  Good to know.  Just different than before.
