### ISSUE TITLE
[API] Requesting too fast. Retrying in 10 seconds… 

### ISSUE THREAD

**Issue by willaertpieter** [OpenPoGo/OpenPoGoBot#153]
[2016-08-01 11:55:39] [+] Login to Pokemon Go successful.
[API] API call failed. Retrying in 10 seconds...

Any ideas how this issue can be fixed?

**Comment by wchill** [comment]
We have no idea what's causing this unfortunately.

**Comment by willaertpieter** [comment]
Issue is fixed when I removed

**Comment by willaertpieter** [comment]
Issue was fixed when I removed:
 
   "gmapkey": "GOOGLE API KEY",
    "google_directions": false,

from my config.json file.

**Comment by nue-melexis** [comment]
I assume it comes from plugins which all make API calls on boot up. 
Maybe it is possible to let only the bot do certain API calls (some read-only data like inventory) . 
Plugins could use that data instead of refreshing over and over.

**Comment by Rifbjerg** [comment]
Just startet for me also 2 hours ago.. everything worked perfect for several days, now i only get this error.. I ran to threads on the same machine, don't know if that actually has anything to do with the error?

**Comment by Rifbjerg** [comment]
As shown here it's the PGoAPI, why that errors is hit, i have no idea

try:
                results = request.call()
            except ServerSideRequestThrottlingException:
                # status code 52: too many requests
                print("[API] Requesting too fast. Retrying in 10 seconds...")
                time.sleep(10)
                continue

**Comment by rrobert45** [comment]
Same for me, just getting [API] Requesting too fast. Retrying in 10 seconds...
![image](https://cloud.githubusercontent.com/assets/20824647/17382759/7c62df82-59a0-11e6-99c8-e91872975ee7.png)

**Comment by wanderingconfused** [comment]
My bots have been generating nothing but that error for at least an hour. They haven't been able to do anything since ptc and google login went down at 15:00 cst.

**Comment by MaxLeiter** [comment]
Most likely this is due to protobuf changes; we're looking into it, and are keeping an eye out for a fix upstream in the API.

**Comment by ghost** [comment]
found this: https://github.com/PocketMobsters/PokeMobBot/commit/52e7c7b6ba398eb9c96fd007be168513f9bed44a

[Edit]
and this:https://www.reddit.com/r/pokemongodev/comments/4w124h/pokemon_go_antibots_reverse_engineering/

just wait and see..

**Comment by wchill** [comment]
These are two separate issues. The first issue is unrelated to the new API changes.

**Comment by meyer9** [comment]
If this is a bug with **our** repo, then reopen this issue, but I'll close it for now.
