### ISSUE TITLE
Egg Hatching

### ISSUE THREAD

**Issue by 1karu5** [OpenPoGo/OpenPoGoBot#160]
@andythorne 
You deleted the fill incubators part from old WalkTowardsFortWorker object ;)

https://github.com/OpenPoGo/OpenPoGoBot/blob/edc4dddbb58fd029b473cfac827d452b18a2a20d/pokemongo_bot/cell_workers/walk_towards_fort_worker.py#L22

We need to find another place for it.
#97

**Comment by andythorne** [comment]
Hm, not sure why egg hatching was in the walk worker but It must of gone in while I was refactoring.

I'll make an event for it.

**Comment by wchill** [comment]
This should be its own plugin

**Comment by 1karu5** [comment]
yes, now that it is possible it should

**Comment by andythorne** [comment]
it's next on my task list.
