### ISSUE TITLE
Refactor lost  login player information print

### ISSUE THREAD

**Issue by dbmurphy** [OpenPoGo/OpenPoGoBot#162]
### Expected Behavior

API token login should be printing user information
### Actual Behavior

Refactor removed this and should be added back. This player data was broken into a function so it could be called in multiple places but always would print level, stardust, EXP, items, Pokemon count, etc. 
### Steps to Reproduce

This is always the case when running
### Other Information

OS: 
Git Commit:

**Comment by andythorne** [comment]
Closing as duplicate of #164
