### ISSUE TITLE
Initial Transfer Issue

### ISSUE THREAD

**Issue by ch333** [OpenPoGo/OpenPoGoBot#163]
### Expected Behavior

Initial transfer is supposed to respect -c for the max CP limit
### Actual Behavior

Error: ambiguous option: -c could match -camp, -cp
### Steps to Reproduce

Run with -it flag set and a -c value
### Other Information

OS: OS X

**Comment by wchill** [comment]
Use `-cp`.

**Comment by ch333** [comment]
Let's fix it in the read me doc.
