### ISSUE TITLE
Suggestion - Print character stats and items

### ISSUE THREAD

**Issue by jonathanbalagot** [OpenPoGo/OpenPoGoBot#164]
Not sure if this was ever brought up.

It would be awesome if your character stats (bag count, exp, etc) and item count for all items is displayed every X amount of time.

**Comment by fonix232** [comment]
How about instead of a continuous log, making a [curses](https://docs.python.org/2/library/curses.html) based UI?

I understand that this is a lot of refactor, but it could show current status (items, eggs, level, XP, etc.), log, and whatnot.

**Comment by dbmurphy** [comment]
Given token regeneration is every 30 minutes, we should consider at least just printing it there  on any re-login.  We had this before but it got lost. Would that work as a solution until something more web/curses based could be considered?

**Comment by MaxLeiter** [comment]
@fonix232 I'm definitely for a curses based UI, but I think the refactoring required would be too much. Once the bot is finished being refactored as is (thanks to the great work by @wchill and @andythorne) I'm willing to look into it more, but as of now I don't think it should be a priority. That being said, however, feel free to give it a try and make a PR!

**Comment by fonix232** [comment]
@MaxLeiter unfortunately my Python knowledge is close to nil - last time I used it, I was still on an S60v3 Nokia phone!

**Comment by niicojs** [comment]
We should close this one. That is what the GUI is for.
