### ISSUE TITLE
OpenPoGoBot seems conflicting with Google Play Service

### ISSUE THREAD

**Issue by lazyfai** [OpenPoGo/OpenPoGoBot#174]
### Expected Behavior
- Android phone no problem using Google service while OpenPoGoBot is running on PC.
### Actual Behavior
- Originally Android phone works well (I have 4.4, 5.0 and 6.0 devices, all the same behavior)
- Once OpenPoGoBot has been ran for a few hours (or some API / login failure happened), all the Android phones asked me to re-login Google account
### Steps to Reproduce
- Get yourself an Android device and login a Google account
- Use the same account for OpenPoGoBot
- Wait for a few hours or until API / login failure happened
- Your Android device will ask you to login again on notification bar
### Other Information

OS: Linux / Mac
Git Commit: latest

**Comment by wchill** [comment]
You should not be using this on your main account, but I'll keep this in mind.

**Comment by lazyfai** [comment]
Just for my curious, wanna know if it is about use of Google Map Key or other things, as Pokemon Go should not be related to Google Play...

**Comment by andythorne** [comment]
i made a fake google account to test a bot on. I literally signed up, got a gmaps key and started the pokemon account. Within 20 mins google had blocked the account for "Suspicious Activity", so it looks like google track the auth requests when using pokemongo.

**Comment by lazyfai** [comment]
I also tried but with different account for player and map key, the account being log out is the player account, the map key account is working well.

**Comment by wchill** [comment]
What happens if you use an app password (as if 2 factor authentication was enabled)?

**Comment by lazyfai** [comment]
Both 2-step with app password and normal password (no MFA) got the same behavior.

**Comment by epicblood** [comment]
I use a gmaps api key from my main account, and have had no issues.
could be because I use a seperate account to login to pogo, however this one doesnt get logged out or anything

**Comment by 1karu5** [comment]
are you running the bot at a different location or ip than your phone? maybe google things your account got hacked because of that

**Comment by lazyfai** [comment]
I think this should not be the case, one people can have more than one phone, probably one left at home and one in office or on street.
And Google API only being used during authentication not during gameplay.

> are you running the bot at a different location or ip than your phone? maybe google things your account got hacked because of that

**Comment by meyer9** [comment]
Closed for issue cleanup.
