### ISSUE TITLE
Unicode Errors (System specific)

### ISSUE THREAD

**Issue by GucciChen** [OpenPoGo/OpenPoGoBot#175]
when i start it .it can work ,after find a pokemon  ,it down  

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 11: ordinal not in range(128)

please help me

**Comment by Reaver01** [comment]
https://github.com/OpenPoGo/OpenPoGoBot/pull/159
This should fix that, but it needs tested
what system are you running this on?

**Comment by Reaver01** [comment]
this is a dupe closing

**Comment by GucciChen** [comment]
kali rolling

**Comment by Reaver01** [comment]
can you give me the output of:

```
import platform  
platform.system()
```

**Comment by GucciChen** [comment]
import platform  ? input terminal ?
there is noithing

**Comment by 1karu5** [comment]
in python console
