### ISSUE TITLE
Low CP/IV Pokemon not recycled after capture

### ISSUE THREAD

**Issue by dbmurphy** [OpenPoGo/OpenPoGoBot#180]
### Expected Behavior

Low value  CP pokemon should be recycled
### Actual Behavior

{'pokemon_potential': 0.7, 'navigator': 'fort', 'cp': 600, u'item_filter': {1: {u'keep': 100}, 2: {u'keep': 100}, 3: {u'keep': 100}, 4: {u'keep': 100}, 101: {u'keep': 10}, 102: {u'keep': 30}, 103: {u'keep': 30}, 201: {u'keep': 30}, 701: {u'keep': 100}}, 'navigator_waypoints': [], 'initial_transfer': True, 'navigator_campsite': None, 'recycle_items': True, 'location_cache': False, 'ign_init_trans': '', 'exclude_plugins': [''], 'fill_incubators': True, use_all_incubators': False, 'distance_unit': u'km', u'mode': u'all', 'debug': False, 'max_steps': 150}
...

2016-08-02 12:44:59] [Catch] A wild Rattata appeared! [CP 164] [Potential 0.69]
[2016-08-02 12:45:01] [Catch] Using Pokeball... (122 left!)
[2016-08-02 12:45:02] [Catch] Rattata has been caught! (CP 164, IV 0.69)
[2016-08-02 12:45:02] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-02 12:45:20] [Catch] A wild Pidgey appeared! [CP 10] [Potential 0.22]
[2016-08-02 12:45:23] [Catch] Using Pokeball... (121 left!)
[2016-08-02 12:45:23] [Catch] Pidgey has been caught! (CP 10, IV 0.22)
[2016-08-02 12:45:23] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
[2016-08-02 12:46:13] [#] Walking from

As you can see no recycle occurred  with pokemon failing under BOTH the IV and the CP limits. 
### Steps to Reproduce

Use master and simply run the box
### Notes

This is one of MANY cases since the refactor where behavior was broken, it should be considered rolling back these changes until that branch can be fixed to be 100% compatible with expected behaviors.
### Other Information

OS:  OSX
Git Commit: 6e22239f214e825d668124aacd570920077b03eb

**Comment by andythorne** [comment]
Easy with the tone @dbmurphy, we're all working in our own time here and are not claiming master is stable at the moment.

Recycling is currently being done when the pokedeck is full rather than on each capture.

Thanks for raising the issue.

**Comment by Saturate** [comment]
I think the current behavior is fine, you can always turn on `--initial-transfer` if you want to clean up a bit when starting the bot.

**Comment by dbmurphy** [comment]
I think the tone is justified as I did contribute and saw many things backed out at there was not acceptable testing or making sure the refactor didn't break things so far I have counted 9 things that were not ported correctly or tested. 

As a contributor what is the reason to give back to a project that is breaking features while trying to claim to be more stable?  Until the refactor is was actually more stable but the refactor itself was not managed well when merged and tested causing instablity. Additionally, it makes one loathe to help out if their changes will just be lost and the code base is unstable due to lack of testing. 

@Saturate If you notice that is on but your expecting the both is not left running for a long time, in this case both are used.

**Comment by andythorne** [comment]
When the deck is full it will clear out so nothing is really broken, it's just changed when it is run.

It is true that we need better testing. Unit and Functional testing will be coming, and with it better stability.

The refactor was required and has provided us with a much more solid base to build on. It was obviously not our intention to remove functionality.

In the meantime, this issue has been added to our backlog (unless you would like to contribute some more).

**Comment by Rlewisrlou666** [comment]
Can it not be set up in the catch Pokemon script?
So have a list of all the Pokemon with a true or false action tied to them?
Kind of killing 2 birds with one stone. 
Let's you tell the bot what to catch and what to ignore.
