### ISSUE TITLE
Does not incubate eggs

### ISSUE THREAD

**Issue by Saturate** [OpenPoGo/OpenPoGoBot#181]
### Expected Behavior

Starts incubation of eggs, when it can.
### Actual Behavior

Does nothing, logged in with phone and no eggs had started incubation.
### Steps to Reproduce
1. Have eggs
2. Run bot
### Other Information

OS: Windows 7
Git Commit: master

Edit: Might be fixed with 5dafadc4c8b06e068c84b4dd000727f925faa261 but haven't tested yet.

**Comment by andythorne** [comment]
What config settings are you using? 

It was working for me this morning with:

```
    "incubation_fill": true,
    "incubation_use_all": true,
    "incubation_priority": ["10km", "5km", "2km"],
    "incubation_restrict": {
        "2km": 901
    },
```

**Comment by Saturate** [comment]
Older ones, I guess 5dafadc4c8b06e068c84b4dd000727f925faa261 might have fixed it. I'm trying right now. Will reopen if it's not working.
