### ISSUE TITLE
JSON catchable, inventory, location in web folder

### ISSUE THREAD

**Issue by pokemon-masterbater** [OpenPoGo/OpenPoGoBot#182]
Can we get the writing of catchable Pokemon, inventory count, and location written to the web folder again? I believe you guys are going to sockets soon but some of us really loved the json file feature

**Comment by epicblood** [comment]
you already opened this issue 3 days ago in #124 
it was addressed there that it is being phased out and will be fixed soon.
Please don't make duplicate issues.
