### ISSUE TITLE
i use proxy and it can not work 

### ISSUE THREAD

**Issue by GucciChen** [OpenPoGo/OpenPoGoBot#188]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcca98be050>: Failed to establish a new connection: [Errno 111] Connection refused',))

i use gae proxy with proxychains

**Comment by epicblood** [comment]
theyve blocked cloud providers like aws so if your proxy goes through one of those that could be why.

**Comment by yusufRahmatullah** [comment]
set environment variable first, HTTP_PROXY and HTTPS_PROXY
if u use windows:
set HTTP_PROXY=http://username:password@host:port
set HTTPS_PROXY=http://username:password@host:port
if u use linux:
export HTTP_PROXY=http://username:password@host:port
export HTTPS_PROXY=http://username:password@host:port

if u want to unable proxy (u must do it coz there is a bug on urllib3):
[windows] set NO_PROXY=127.0.0.0/8
[linux] set NO_PROXY=127.0.0.0/8

hope it can help

**Comment by GucciChen** [comment]
@yusufRahmatullah thanks ,it's ok
