### ISSUE TITLE
in catch plugins this iv culculate is not right.

### ISSUE THREAD

**Issue by adventurer** [OpenPoGo/OpenPoGoBot#189]
elif status is 1:
        **log('{} has been caught! (CP {}, IV {})'.format(pokemon_name, combat_power, pokemon_potential), 'green')**
        xp = pokemon_catch_response.xp
        stardust = pokemon_catch_response.stardust
        candy = pokemon_catch_response.candy
        log("Rewards: {} XP, {} Stardust, {} Candy".format(xp, stardust, candy), "green")
        return False

**Comment by wchill** [comment]
Need more information.

**Comment by andythorne** [comment]
Seems fine to me...

https://github.com/OpenPoGo/OpenPoGoBot/blob/master/api/pokemon.py#L27
