### ISSUE TITLE
Bot crashes on printing PokeStops name with utf8 characters

### ISSUE THREAD

**Issue by GutZuFusss** [OpenPoGo/OpenPoGoBot#191]
### Expected Behavior

Bot prints the PokeStop's name correctly
### Actual Behavior

Bot crashes while calling the log function:
`[2016-08-03 01:50:12] [#] Now at PokeStop "Joh. Jos. Couven Wespienhaus 1737"
Traceback (most recent call last):
  File "pokecli.py", line 347, in <module>
    main()
  File "pokecli.py", line 340, in main
    bot.run()
  File "/home/pi/OpenPoGoBot/pokemongo_bot/__init__.py", line 92, in run
    self.navigator.navigate(map_cells)
  File "/home/pi/OpenPoGoBot/pokemongo_bot/navigation/fort_navigator.py", line 40, in navigate
    logger.log("[#] Walking towards PokeStop \"{}\" ({} away)".format(fort_name, format_dist(dist, unit)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)`
### Steps to Reproduce

Set "50.776309, 6.083505" as location and wait some time. Other locations with PokeStops that have unicode characters in it should work aswell.
### Other Information

OS: Linux Mint Debian Edition
Git Commit: dec09ff59257c5c0728c3edc957fee5e3b974701

**Comment by Saturate** [comment]
Fixed in #159

**Comment by GutZuFusss** [comment]
Thanks for pointing me in the right direction.
