### ISSUE TITLE
Suggestion: `--initial-transfer` alternative based on IV instead of CP

### ISSUE THREAD

**Issue by tegob** [OpenPoGo/OpenPoGoBot#193]
Documentation for `--initial-transfer`:

> Start the bot with a pokemon clean up, keeping only the higher CP of each pokemon. It respects `-c` as upper limit to release.

It would be nice to have something similar but based on potential/IV instead of CP.

**Comment by andythorne** [comment]
The docs are wrong, it does on both iv and cp. Set `config.cp=0` and `config.pokemon_potential` to the iv value (0.0 - 1.0)

**Comment by faegan** [comment]
Correct, initialen transfer takes info account CP and IV. Documentation needs to be changed.

**Comment by faegan** [comment]
Autocorrect on phone :( initial transfer takes into account ...

**Comment by tegob** [comment]
Is there an command-line flag equivalent to `-c` (upper CP limit okay to release) for IV?

**Comment by tegob** [comment]
Ah, that’s probably `--pokemon-potential`. I’ll update the docs.

**Comment by andythorne** [comment]
Yep that's right :)

Thanks!

**Comment by tegob** [comment]
I’ll also assume that `-c` is a typo for `-cp`. ;)

**Comment by tegob** [comment]
PR: #197. Closing this issue.
