### ISSUE TITLE
[APi] Requesting too fast.

### ISSUE THREAD

**Issue by banaszeknorbert** [OpenPoGo/OpenPoGoBot#198]
This happens after successful logging. I'm getting this:
[2016-08-03 23:57:21] [x] Starting PokemonGo Bot....
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
Does anyone have a similar problem? Is Niantic changed something in the api?

**Comment by ghost** [comment]
same here since about 2 hours

**Comment by banaszeknorbert** [comment]
Ok, I found this: https://www.reddit.com/r/pokemongo/comments/4vvpbw/niantic_is_upping_the_scan_refresh_rate_to_break/

Could someone tell me where I can change this value?

**Comment by wchill** [comment]
All bots are broken at the moment. Nothing we can do right now.

**Comment by banaszeknorbert** [comment]
Increasing the refresh rate will not work?

**Comment by MaxLeiter** [comment]
Duplicate of #153

**Comment by wchill** [comment]
Not actually a duplicate of #153, but fixed in #202.
