### ISSUE TITLE
This feature is being removed by major browsers and deprecated by RFC 2818 and api can't work 

### ISSUE THREAD

**Issue by GucciChen** [OpenPoGo/OpenPoGoBot#199]
/usr/local/lib/python2.7/dist-packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for android.clients.google.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/usr/local/lib/python2.7/dist-packages/urllib3/connection.py:303: SubjectAltNameWarning: Certificate for pgorelease.nianticlabs.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

[2016-08-04 09:21:11] [x] Starting PokemonGo Bot....
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] API call failed. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...
[API] Requesting too fast. Retrying in 10 seconds...

**Comment by wchill** [comment]
Deprecation issue is not fixable by us.

2nd issue will be closed by #202.
