### ISSUE TITLE
Refactor of Bot Object

### ISSUE THREAD

**Issue by jtdroste** [OpenPoGo/OpenPoGoBot#20]
This is going to be dirty ticket.
- [x]  Create a user object to contain information about the logged in user
- [x] Create a plugin subsystem to call before/after a cell_worker
- [x] Create the ability to make different stepper algos
- [x] Bot object will only be responsible for setting up the API, and a few other objects
- [x] Bot object will be moved to a different file, rather than **init**

**Comment by wchill** [comment]
Also, documentation

**Comment by wchill** [comment]
User object was created in #112.

**Comment by wchill** [comment]
#270 should help with 4th checkbox.

**Comment by andythorne** [comment]
@wchill, yep you're right. I'm planning on moving all the player and pokemon action logic to their own services.

**Comment by andythorne** [comment]
In fact, I could handle 5th checkbox in that provides as well...

**Comment by andythorne** [comment]
*in that PR as well... 

Phone autocorrect  :(

**Comment by meyer9** [comment]
5 done with #270

**Comment by meyer9** [comment]
I's say this issue is about ready to be closed. :+1:

**Comment by andythorne** [comment]
I'd agree, good job all! :+1:
