### ISSUE TITLE
Suggestion: Evolve Pokemon using customizable parameters.

### ISSUE THREAD

**Issue by plgonzalezrx8** [OpenPoGo/OpenPoGoBot#204]
What the title says, it would be a good feature to evolve pokemon based on preset values for best experience, or customizable values.

**Comment by epicblood** [comment]
I can work on this after #194 is merged and tested.
will need some input on what kind of customization you want

**Comment by plgonzalezrx8** [comment]
So here's what I was thinking about adding a third mode, that will make it Farming Pokestops, Catching Pokemon and Evolving Pokemon. The evolving part can take place before "mass transfering" that usually happens. Personally, I prefer the "mass transfering" instead the transfer after catching, that way I can just stop the script and do the evolving manually.

These are the parameters I was thinking about
- Evolve all pokemon that can be evolved, this can be set to true or false.
- Filter evolutions by pokemon (Pidgeys, Caterpies, Etc), which can be combined with the first parameter, evolving all pidgeys, caterpies, etc. 
- Evolve only pokemon above certain CP or IV, set the evolveallpokemon to false and put the minimum IV or CP to evolve, or a combination of both.
- and for those who prefer the transfer after capture, there can be an option to evolve then transfer if it meets the criteria in the config file.
