### ISSUE TITLE
[Question] encrypt library

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoBot#205]
Any detailed info about encrypt library?

Running **make** inside lib folder returns:
`
make: *** No rule to make target 'encrypt.o', needed by 'libencrypt.so'.  Stop.
`

**Comment by Waliers** [comment]
ReadMe says: find **libencrypt.so**. Put it in the lib folder and run _make_ again.

**Comment by ghost** [comment]
That library isn't needed, make script should make it. 
Needed for make script is 'encrypt.o', but i don't know from where i should get it.

**Comment by ghost** [comment]
ok, nevermind. found it.
