### ISSUE TITLE
libencrypt.so

### ISSUE THREAD

**Issue by GucciChen** [OpenPoGo/OpenPoGoBot#206]
libencrypt.so: cannot open shared object file: No such file or directory

**Comment by acalinp** [comment]
What I did, you are on Linux I assume, is edit the venv/src/pgoapi/pgoapi/pgoapi.py file such that lib_path points to the absolute location of my compiled libencrypt.so file
![screenshot_20160807_141256](https://cloud.githubusercontent.com/assets/9417983/17462060/1356036e-5ca9-11e6-8fcd-b75a18597bb8.png)

**Comment by epicblood** [comment]
you need to compile encrypt.c into libencrypt.so.
encrypt.c cannot be distributed, so you will have to find it on your own.

**Comment by lazyfai** [comment]
I used "LD_LIBRARY_PATH" environment variable to specify the path to the so file.

**Comment by yuyaukong** [comment]
I am using mac os, how can I find "encrypt.c"? Since I search on finder cannot see any related material. Could anyone give me some suggestion?

**Comment by yuyaukong** [comment]
Sorry, I found the solution in here: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2778

**Comment by GucciChen** [comment]
OSError: libencrypt.so: cannot open shared object file: No such file or directory
