### ISSUE TITLE
Cannot generate encrypt.dll on Windows

### ISSUE THREAD

**Issue by g2384** [OpenPoGo/OpenPoGoBot#207]
### Actual Behavior

run build_dll.bat as admin, no file is generated.
Do I need ecrypt.c? Where is it?
### Other Information

OS: Windows 10
Git Commit: 

**Update:** Ok, found the encrypt.dll online

**Comment by epicblood** [comment]
you have to find it on your own as it is copyrighted. I suggest you check pgoapi.com
