### ISSUE TITLE
Can't compile encrypt.so on ubuntu 

### ISSUE THREAD

**Issue by CryptoSiD** [OpenPoGo/OpenPoGoBot#208]
Greetings,
I'm following the instruction to compile encrypt.so but here's the result

To build the shared library for OS X or Linux, in the lib folder run make, rename the resulting binary as needed and move to the bot folder. (copied from the README.md)

root@CryptoSiD:~/OpenPoGoBot/lib# make
make: **\* No rule to make target 'encrypt.o', needed by 'libencrypt.so'.  Stop.
root@CryptoSiD:~/OpenPoGoBot/lib# 

What am I missing?

**Comment by ghost** [comment]
> You will need to either find encrypt.c or the appropriate shared library for your system. The bot will automatically attempt to load the following filenames; another filename can be specified using config options as described below.

You have to find the encrypt.c (or the libencrypt.so what you try to build) by your own. 
I guess due to copyright or legal rights ..

**Comment by CryptoSiD** [comment]
Ho well.... what if I'm unable to find it? Look like i can't use that bot anymore

**Comment by Dimitrie78** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2778

**Comment by CryptoSiD** [comment]
thanks a lot

**Comment by tehp** [comment]
For anyone wondering in the future:
http://pgoapi.com/
