### ISSUE TITLE
Bot walking in circles

### ISSUE THREAD

**Issue by alexandre-leites** [OpenPoGo/OpenPoGoBot#219]
### Expected Behavior

Bot randomize its behavior and walk from these pokestops.
### Actual Behavior

Bot just walk in circles going to the same pokestops.
Image: http://imgur.com/Uk97kFr
### Steps to Reproduce

Santa Monica Pier
### Other Information

OS: W10
Git Commit: Master

**Comment by andythorne** [comment]
Try increasing your max_steps config setting. 

The bot also ranks the stops in distance order which is why it repeats the same path.

**Comment by meyer9** [comment]
Reopen if still an issue.
