### ISSUE TITLE
making the encrypt.so on linux

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoBot#220]
Hey, i cannot make an encrypt.so on my linux machine...

When i cd into 'lib' folder and call make, i get : 

 No rule to make target 'encrypt.o', needed by 'libencrypt.so'.  Stop.

Am I doing something wrong?

**Comment by wchill** [comment]
`encrypt.c` is required to build `libencrypt.so`. Please read the README for more details.
