### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jhwayne** [OpenPoGo/OpenPoGoBot#224]
### Expected Behavior

Start bot, input location have bot working normally no erros.
### Actual Behavior

When walking to a PokeStop I get an IndexError
### Other Information

OS: 

Anytime it is walking to a PokeStop it throws "IndexError: list index out of range" everything else seems to work, anything before walking to PokeStop ( catching pokemon, transfering,etc works) breaks when walking. 
Git Commit:

**Comment by AlexDevelop** [comment]
Possible it's because of the following:

> baconcake: the problem is that you had maybe 1 subrequest, but the server delivers 2 answers. therefore this loop crashes with i=1 because subrequests_list has only 1 element which you requested

Also by baconcake ("i'm using this for the offending line in rpc_api.py"):

```
            try:
                request_entry = subrequests_list[i]
            except IndexError:
                self.log.error("More responses came back than I requested! i=%d" % i)
                continue
```

I myself added a try/except around bot.run() so it continues

**Comment by wchill** [comment]
This is an upstream issue, waiting on a fix.

**Comment by jhwayne** [comment]
Yeah I just pulled the latest and that error is gone, however a new error has replaced it with, 

AttributeError: 'Destination' object has no attribute 'steps'

Guess I will wait for some changes and see if it gets solved.

**Comment by registered99** [comment]
Change `format_time(len(destination.steps))),` to `format_time(len(destination.step()))),` in stepper.py

**Comment by wongjustin98** [comment]
Change `format_time(len(destination.steps))),` to `format_time(len(destination._steps))),` in stepper.py

Not sure of the proper code fix, but this gets the bot back running.

**Comment by MaxLeiter** [comment]
@jhwayne #227 should have fixed your problem, can you confirm? @registered99

**Comment by l3uddz** [comment]
@MaxLeiter fixed it for me.

**Comment by wongjustin98** [comment]
@MaxLeiter Yup, fixed it for me

**Comment by jhwayne** [comment]
Yup, I just pulled the latest and everything is working now.
