### ISSUE TITLE
Ignore Pokemon Yaml file not working

### ISSUE THREAD

**Issue by jhwayne** [OpenPoGo/OpenPoGoBot#226]
Having issues here, I updated the YAML file with just the example Pokemon and I am still catching them. Is there anything else that needs to be done to ensure they are going to be ignored?

**Comment by wchill** [comment]
Not supported at the moment.

**Comment by meyer9** [comment]
We might want to move this to a different branch if it's not supported ATM.

**Comment by wchill** [comment]
Waiting for #286 and #270 to be merged before this can be fixed.

**Comment by meyer9** [comment]
Should be fixed with #286
