### ISSUE TITLE
Error during normal operation

### ISSUE THREAD

**Issue by clolin** [OpenPoGo/OpenPoGoBot#233]
### Expected Behavior

Expected behavior is to find, catch and proceed to next closet pokestop.
### Actual Behavior

Three successive API call failures, followed by seven informational messages indicating the client was requesting too fast.
### Steps to Reproduce

Symptoms were observed during normal operations, no additional actions were taken preceding the problem.
### Other Information

OS: Ubuntu Linux 16.04.1
Git Commit: 1019e988e0bb23b37c0be55735f316e06a2ed959
[NoneTypeError.08AUG2016.txt](https://github.com/OpenPoGo/OpenPoGoBot/files/407989/NoneTypeError.08AUG2016.txt)

**Comment by clolin** [comment]
```
> [API] API call failed. Retrying in 10 seconds...
> [API] API call failed. Retrying in 10 seconds...
> [API] API call failed. Retrying in 10 seconds...
> [API] Requesting too fast. Retrying in 10 seconds...
> [API] Requesting too fast. Retrying in 10 seconds...
> [API] Requesting too fast. Retrying in 10 seconds...
> [API] Requesting too fast. Retrying in 10 seconds...
> [API] Requesting too fast. Retrying in 10 seconds...
> [API] Requesting too fast. Retrying in 10 seconds...
> [API] Requesting too fast. Retrying in 10 seconds...
> Traceback (most recent call last):
>   File "pokecli.py", line 371, in <module>
>     main()
>   File "pokecli.py", line 364, in main
>     bot.run()
>   File "/home/user/OpenPoGoBot/pokemongo_bot/__init__.py", line 116, in run
>     self.mapper.get_cells_at_current_position()
>   File "/home/user/OpenPoGoBot/pokemongo_bot/__init__.py", line 126, in work_on_cells
>     for cell in map_cells:
> TypeError: 'NoneType' object is not iterable
```

**Comment by tehp** [comment]
I've never seen this before.
Are you still getting this on latest master?

**Comment by clolin** [comment]
Just updated now, will test overnight and observe.

**Comment by meyer9** [comment]
going to close this. feel free to reopen it if this is still a problem
