### ISSUE TITLE
Suggestion: The ability to use set up a proxy server when running the bot.

### ISSUE THREAD

**Issue by plgonzalezrx8** [OpenPoGo/OpenPoGoBot#235]
I am using an cloud linux virtual environment and I believe I am not able to run the bot because the pokemon servers have my provider IP banned (Pythonanywhere), would like to have the option to setup a proxy server when running the bot.

**Comment by prophaner** [comment]
I would like to see a common proxy library like proxy.py and an embedded solution like Stem (Tor), then a flag that recognizes when the IP has been banned to switch proxied IP. I'll work on it if I have time

**Comment by tehp** [comment]
Can I ask why you don't just run the script locally?

**Comment by plgonzalezrx8** [comment]
Cannot install applications at work or connect to my computer remotely so I use pythonanywhere since its a webinterface.

**Comment by tehp** [comment]
I see. This is quite an edge case, so unless you write this, I can't see it being done any time soon.

**Comment by plgonzalezrx8** [comment]
Its okay. :) Thanks a lot for your help and at least considering the suggestion, I think it will be easier for me to write a program that let me connect to my home bash console from pythonanywhere. I'm not that good at writing code yet, been writing python only for 6 months.

**Comment by wchill** [comment]
Closing as proxy support is unneeded.
