### ISSUE TITLE
OSError: encrypt.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JandersonFB** [OpenPoGo/OpenPoGoBot#256]
Please, how to fix ?

OSError: encrypt.so: cannot open shared object file: No such file or directory

http://image.prntscr.com/image/6f265c547a014cab92c31168ba085489.jpeg
### Other Information

OS: Ubuntu
Git Commit:  Last

**Comment by joseph-abell** [comment]
We cannot give you encrypt.so with the code, as this would break licencing. I would suggest to read the README that comes with the code, as it will point you in the correct direction.
