### ISSUE TITLE
Bot cant find pokestops!

### ISSUE THREAD

**Issue by smilezs** [OpenPoGo/OpenPoGoBot#262]
Hey

my bot just says

we cant find any pokestops that unnused and that all the time at newyork pls help

thx :)

**Comment by niicojs** [comment]
Try increasing max steps in config. But it seems unlikely to be a problem in NY...

**Comment by wchill** [comment]
This can happen if your IP is banned due to ratelimiting. Use only one bot or turn off any mapping services that you are running.
