### ISSUE TITLE
Have command line parameters take priority over JSON

### ISSUE THREAD

**Issue by MaxLeiter** [OpenPoGo/OpenPoGoBot#27]
This is definitely open for discussion. I'm personally a fan of removing JSON configuration files and going back to command line parameters. At least give command line priority over JSON (So you can use both but if there's a conflict command line is used).

**Comment by wchill** [comment]
Alternatively, add a switch so that JSON must be explicitly loaded.

**Comment by joseph-abell** [comment]
I like having the option, I like the permenancy of a json file. Something needs to change: this halfway version isn't good enough.
