### ISSUE TITLE
Add a random sleep before request.call()

### ISSUE THREAD

**Issue by robertyu** [OpenPoGo/OpenPoGoBot#271]
I did some test, add

```
api_cd = random.uniform(0.5,2.5)
#print("[API] CD before requesting in " + str(api_cd) + " seconds.")
time.sleep(api_cd)
results = request.call()
```

"[API] Requesting too fast. Retrying in 10 seconds". no more happening.

**Comment by PhilippHeuer** [comment]
Where did you put that?

**Comment by robertyu** [comment]
`/api/__init__.py`  inside `def call(self, ignore_expiration=False, ignore_cache=False):`

**Comment by robertyu** [comment]
Maybe change the human_behaviour.py => sleep is a better way

**Comment by cypherlou** [comment]
in `api/__init__.py`
`import random`
line 97:
`api_cd = random.uniform(0.5,2.5)`
`time.sleep(api_cd)`
 `try:`
    `results = request.call()`

**Comment by xasdf** [comment]
@robertyu this is pretty good!
I'm running with "time.sleep(random.uniform(0.5, 1.5))" and haven't seen throttling messages so far.

**Comment by meyer9** [comment]
submit a pull request so we can add it to the project. 👍

**Comment by PhilippHeuer** [comment]
I also didn't get this message again. I'm using a delay of 0.5 - 1.5 too.

The startup of the bot also is way faster now, maybe it's just me? (time after login until the bot starts working)
