### ISSUE TITLE
Possible UI Change only

### ISSUE THREAD

**Issue by lifeiscontent** [OpenPoGo/OpenPoGoBot#273]
Would be nice to see how many Pokemon you have in total for the ones you remove in the UI.

E.g: `Are you sure you want to transfer this Pokemon?`

to: Are you sure you want to transfer this Pokemon? You have **5** Pidgy's left

If this isn't the right repo to open an issue for this on, please let me know. 👍

**Comment by niicojs** [comment]
you you recreate this into the openpogoui project?
