### ISSUE TITLE
Error 193 OS: Windows 8

### ISSUE THREAD

**Issue by jordi3333** [OpenPoGo/OpenPoGoBot#274]
Expected Behavior: the bot starting

Actual Behavior: CMD gives the following error: WindowsError: [Error 193] 1% is not a valid Win32-Application

Other Information: This is what it looks like and the command i used was ( python pokecli.py -a google -u my email -p my password --location ''New York, Washington Square"

https://gyazo.com/cdd596f1a29d0cbd28c974716aec5595

I am not a programmer myself but i have been busy with downloading a pokemongobot for the past couple of days and i have learned a ton. If anyone could help out that would be great.

**Comment by wchill** [comment]
You are most likely using a 64-bit version of Python. You need to find a 64-bit version of `encrypt.dll`.

**Comment by jordi3333** [comment]
I used the 64 bit version which i downloaded here https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom/libencrypt

**Comment by niicojs** [comment]
so maybe the other way around :)
maybe you have python 32, try encrypt32

**Comment by jordi3333** [comment]
Thanks the 32bit version works but now i get this: https://gyazo.com/c36c197f6471bd79fa175f37fec567de

**Comment by niicojs** [comment]
seems like your google map key is either missing or incorrect.
(btw, what is this pink console? my eyes are bleeding...)

**Comment by jordi3333** [comment]
Just my customized cmd :P But I have no idea to fix this still since the key is correct and i have directions enabled on google maps.

**Comment by jordi3333** [comment]
I had to enable some more features on google maps. The bot is working now.

**Comment by niicojs** [comment]
good
