### ISSUE TITLE
Should offer option to take over gyms.

### ISSUE THREAD

**Issue by meyer9** [OpenPoGo/OpenPoGoBot#283]
Should offer option to take over gyms. Maybe a setting in config to take over a gym under a certain level?

**Comment by wchill** [comment]
👎 I think we already talked about this; taking over gyms is not a good idea.

**Comment by niicojs** [comment]
I would say this maybe not a very nice move for real players.
But if all other bots are doing this, maybe we should.
I don't really look at what others are doing, do they?

**Comment by plgonzalezrx8** [comment]
Not a good idea to be honest. One thing is having good pokemons and level up, other thing is straight up taking gyms to legit players and have them spend a lot of resources trying to take gyms from botters, just my opinion.

**Comment by PhilippHeuer** [comment]
I agree that auto battling the gym's would not be a nice thing. But we could have the bot go to allied gyms to fill up empty spots?

**Comment by wchill** [comment]
In light of the recent ban wave, I think this should definitely not be implemented.
