### ISSUE TITLE
Socket Map Not Working

### ISSUE THREAD

**Issue by ch333** [OpenPoGo/OpenPoGoBot#290]
### Expected Behavior

Map loads and displays trainer, path, and catches.
### Actual Behavior

Does not load.  Says: Waiting to get GPS coordinates from Bot...
![image](https://cloud.githubusercontent.com/assets/18740534/17630370/33672792-607c-11e6-974c-a78dcabc1f4e.png)
### Steps to Reproduce

Run latest commit.
### Other Information

OS: OS X
Git Commit: a716a34

**Comment by niicojs** [comment]
Did you test with Chrome?
Could you past console log, browser log as well as the result of "pip freeze"?

**Comment by ch333** [comment]
Sorry I didn't include the web browser: chrome, but also occurs on firefox

Typical Console Log:
2016-08-12 11:20:12] [x] PokemonGO Bot v1.0
[2016-08-12 11:20:12] [x] Configuration initialized
[2016-08-12 11:20:12] [Plugins] Loaded plugin "evolver".
[2016-08-12 11:20:12] [Plugins] Not loading plugin "web"
[2016-08-12 11:20:12] [Plugins] Loaded plugin "socket".
[2016-08-12 11:20:12] [Plugins] Loaded plugin "recycle_items".
[2016-08-12 11:20:12] [Plugins] Loaded plugin "catch_pokemon".
[2016-08-12 11:20:12] [Plugins] Loaded plugin "spin_pokestop".
[2016-08-12 11:20:12] [Plugins] Loaded plugin "transfer_pokemon".
[2016-08-12 11:20:12] [Plugins] Loaded plugin "egg_incubator".
[2016-08-12 11:20:13] [Plugins] Plugins loaded: ['catch_pokemon', 'egg_incubator', 'evolver', 'recycle_items', 'socket', 'spin_pokestop', 'transfer_pokemon']
[2016-08-12 11:20:13] [x] Fetching altitude from google
[2016-08-12 11:20:14] 
[2016-08-12 11:20:14] [x] Address found: lat, long
[2016-08-12 11:20:14] [x] Position in-game set as: (lat, long, alt)
[2016-08-12 11:20:14] 
[2016-08-12 11:20:14] Web client connected
[2016-08-12 11:20:16] [+] Login to Pokemon Go successful.
[2016-08-12 11:20:18] [#]
...Trainer Data ...
[2016-08-12 11:20:18] [#]
[2016-08-12 11:20:18] [x] Starting PokemonGo Bot....
...
[2016-08-12 11:21:42] Web client disconnected
[2016-08-12 11:21:42] Web client connected

Occasionally I get this error:

[2016-08-12 11:28:18] Web client disconnected
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/usr/local/lib/python2.7/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/socketio/server.py", line 308, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/engineio/server.py", line 247, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python2.7/site-packages/engineio/server.py", line 359, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'

[2016-08-12 11:28:19] Web client connected

I can provide more logs if you tell me where to look for them.

**Comment by niicojs** [comment]
Run "pip uninstall eventlet"
Send me log from Chrome (ctrl+maj+I) also.
To be sure, are you up to date on github and which url are you using?

**Comment by ch333** [comment]
From the chrome console:

include.preload.js:425 Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.
VM1727:5 Uncaught TypeError: Cannot read property 'removeAttribute' of null(anonymous function) @ VM1727:5(anonymous function) @ VM1727:20
openpogoui.nicontoso.eu/:76 GET http://openpogoui.nicontoso.eu/scripts/ga.js net::ERR_BLOCKED_BY_CLIENT
config.js:63 Load config from storage
jquery-3.1.0.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
socket.js:28 Connecting to http://localhost:8000
socket.js:43 Connected to Bot
socket.js:53 Bot Ready.
socket.js:54 Object {username: "*****", player: Object, storage: Object, coordinates: Array[3], level: 31}
socket.js:59 Uncaught ReferenceError: ga is not definedsocket.on.msg @ socket.js:59Emitter.emit @ socket.io-1.4.5.js:3Socket.emitBuffered @ socket.io-1.4.5.js:3Socket.onconnect @ socket.io-1.4.5.js:3Socket.onpacket @ socket.io-1.4.5.js:3(anonymous function) @ socket.io-1.4.5.js:3Emitter.emit @ socket.io-1.4.5.js:3Manager.ondecoded @ socket.io-1.4.5.js:2(anonymous function) @ socket.io-1.4.5.js:3Emitter.emit @ socket.io-1.4.5.js:2Decoder.add @ socket.io-1.4.5.js:3Manager.ondata @ socket.io-1.4.5.js:2(anonymous function) @ socket.io-1.4.5.js:3Emitter.emit @ socket.io-1.4.5.js:2Socket.onPacket @ socket.io-1.4.5.js:1(anonymous function) @ socket.io-1.4.5.js:1Emitter.emit @ socket.io-1.4.5.js:2Transport.onPacket @ socket.io-1.4.5.js:1callback @ socket.io-1.4.5.js:1(anonymous function) @ socket.io-1.4.5.js:2exports.decodePayloadAsBinary @ socket.io-1.4.5.js:2exports.decodePayload @ socket.io-1.4.5.js:2Polling.onData @ socket.io-1.4.5.js:1(anonymous function) @ socket.io-1.4.5.js:1Emitter.emit @ socket.io-1.4.5.js:2Request.onData @ socket.io-1.4.5.js:1Request.onLoad @ socket.io-1.4.5.js:1xhr.onreadystatechange @ socket.io-1.4.5.js:1

![image](https://cloud.githubusercontent.com/assets/18740534/17632208/64323bac-6084-11e6-839f-db6c6c23422c.png)

**Comment by ch333** [comment]
pip uninstall eventlet:
Uninstalling eventlet-0.19.0:
  /usr/local/lib/python2.7/site-packages/eventlet-0.19.0.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/site-packages/eventlet-0.19.0.dist-info/INSTALLER
  /usr/local/lib/python2.7/site-packages/eventlet-0.19.0.dist-info/METADATA
  /usr/local/lib/python2.7/site-packages/eventlet-0.19.0.dist-info/RECORD
  /usr/local/lib/python2.7/site-packages/eventlet-0.19.0.dist-info/WHEEL
  /usr/local/lib/python2.7/site-packages/eventlet-0.19.0.dist-info/metadata.json
  /usr/local/lib/python2.7/site-packages/eventlet-0.19.0.dist-info/top_level.txt
  /usr/local/lib/python2.7/site-packages/eventlet/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/backdoor.py
  /usr/local/lib/python2.7/site-packages/eventlet/backdoor.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/convenience.py
  /usr/local/lib/python2.7/site-packages/eventlet/convenience.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/corolocal.py
  /usr/local/lib/python2.7/site-packages/eventlet/corolocal.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/coros.py
  /usr/local/lib/python2.7/site-packages/eventlet/coros.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/db_pool.py
  /usr/local/lib/python2.7/site-packages/eventlet/db_pool.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/debug.py
  /usr/local/lib/python2.7/site-packages/eventlet/debug.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/event.py
  /usr/local/lib/python2.7/site-packages/eventlet/event.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/BaseHTTPServer.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/BaseHTTPServer.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/CGIHTTPServer.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/CGIHTTPServer.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/MySQLdb.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/MySQLdb.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/SSL.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/SSL.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/crypto.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/crypto.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/rand.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/rand.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/tsafe.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/tsafe.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/version.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/OpenSSL/version.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/Queue.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/Queue.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/SimpleHTTPServer.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/SimpleHTTPServer.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/SocketServer.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/SocketServer.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/_socket_nodns.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/_socket_nodns.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/asynchat.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/asynchat.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/asyncore.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/asyncore.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/builtin.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/builtin.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/ftplib.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/ftplib.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/client.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/client.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/cookiejar.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/cookiejar.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/cookies.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/cookies.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/server.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/http/server.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/httplib.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/httplib.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/os.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/os.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/profile.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/profile.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/select.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/select.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/selectors.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/selectors.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/socket.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/socket.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/ssl.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/ssl.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/subprocess.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/subprocess.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/thread.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/thread.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/threading.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/threading.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/time.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/time.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/error.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/error.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/parse.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/parse.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/request.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/request.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/response.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib/response.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib2.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/urllib2.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/green/zmq.py
  /usr/local/lib/python2.7/site-packages/eventlet/green/zmq.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/base.py
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/base.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/py2.py
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/py2.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/py3.py
  /usr/local/lib/python2.7/site-packages/eventlet/greenio/py3.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/greenpool.py
  /usr/local/lib/python2.7/site-packages/eventlet/greenpool.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/greenthread.py
  /usr/local/lib/python2.7/site-packages/eventlet/greenthread.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/epolls.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/hub.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/hub.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/kqueue.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/kqueue.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/poll.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/poll.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/pyevent.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/pyevent.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/selects.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/selects.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/timer.py
  /usr/local/lib/python2.7/site-packages/eventlet/hubs/timer.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/patcher.py
  /usr/local/lib/python2.7/site-packages/eventlet/patcher.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/pools.py
  /usr/local/lib/python2.7/site-packages/eventlet/pools.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/queue.py
  /usr/local/lib/python2.7/site-packages/eventlet/queue.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/semaphore.py
  /usr/local/lib/python2.7/site-packages/eventlet/semaphore.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/__init__.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/__init__.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/greendns.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/greendns.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/greenlets.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/greenlets.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/psycopg2_patcher.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/psycopg2_patcher.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/pylib.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/pylib.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/six.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/six.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/stacklesspypys.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/stacklesspypys.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/support/stacklesss.py
  /usr/local/lib/python2.7/site-packages/eventlet/support/stacklesss.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/timeout.py
  /usr/local/lib/python2.7/site-packages/eventlet/timeout.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/tpool.py
  /usr/local/lib/python2.7/site-packages/eventlet/tpool.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/websocket.py
  /usr/local/lib/python2.7/site-packages/eventlet/websocket.pyc
  /usr/local/lib/python2.7/site-packages/eventlet/wsgi.py
  /usr/local/lib/python2.7/site-packages/eventlet/wsgi.pyc
Proceed (y/n)? y
  Successfully uninstalled eventlet-0.19.0

**Comment by niicojs** [comment]
Could you try removing adblock or any other adblock for this domain?
I'll have to fix that later.

**Comment by ch333** [comment]
Ahh! Genesis!  That solved the problem.

Thanks for the help!!!
