### ISSUE TITLE
API call failed. Retrying in 10 seconds...

### ISSUE THREAD

**Issue by Vl4dim1r** [OpenPoGo/OpenPoGoBot#295]
```
[2016-08-12 19:16:03] [+] Login to Pokemon Go successful.
[API] API call failed. Retrying in 10 seconds...
[API] API call failed. Retrying in 10 seconds...
[API] API call failed. Retrying in 10 seconds...
^C[2016-08-12 19:16:36] [x] Exiting PokemonGo Bot
```

API call seems to retry indefinitely until closed. Using latest commit, cloned 45min ago.
Any idea what is causing this?

[UPDATE] letting the script continue results in this:

```
Traceback (most recent call last):
  File "pokecli.py", line 380, in <module>
    main()
  File "pokecli.py", line 368, in main
    bot.start()
  File "/opt/xtt/OpenPoGoBot/pokemongo_bot/__init__.py", line 74, in start
    self._setup_api()
  File "/opt/xtt/OpenPoGoBot/pokemongo_bot/__init__.py", line 176, in _setup_api
    response_dict = self.update_player_and_inventory()
  File "/opt/xtt/OpenPoGoBot/pokemongo_bot/__init__.py", line 213, in update_player_and_inventory
    self.candies = response_dict['candy']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by wchill** [comment]
Try logging in on your phone.

**Comment by Vl4dim1r** [comment]
"Failed to get game data from server." 
Makes sense now. Sorry to post a useless issue. Is everyone getting this? I saw the message earlier and thought it was an intermittent issue like the first week of release.

**Comment by wchill** [comment]
If you're getting that message, it's very likely that you have been permanently banned.

https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
