### ISSUE TITLE
Not use 2 factor authentication but still Login Error, server busy

### ISSUE THREAD

**Issue by yusufRahmatullah** [OpenPoGo/OpenPoGoBot#296]
### Expected Behavior

login success
### Actual Behavior

Login Error, server busy
### Other Information

OS: Raspbian jessie
Git Commit: last commit

**Comment by wchill** [comment]
Possible duplicate of #295.

**Comment by yusufRahmatullah** [comment]
what is info that you needed?
oh yes, i'm trying to using bot in windows 8.1 and it's work
