### ISSUE TITLE
Contributing Standards

### ISSUE THREAD

**Issue by jtdroste** [OpenPoGo/OpenPoGoBot#3]
Right now this will be a brain dump...apologize for the lack of structure.
- All work must be done via PR's - even if done by a maintainer
- All PRs must get two approvals/:+1: from`@OpenPoGo/maintainers` before merging
- All PRs must pass pep8 standards (this will be checked automatically)
- All PRs must pass CI
- One PR per feature
- All PR commits must be concise and squashed (done via the contributor)
- All PRs should be merged via rebase

**Comment by MaxLeiter** [comment]
PR commits should be concise and squashed. One PR per feature, so generally 1 commit per PR (although there may be reasons to have multiple commits, as long as they make sense) imo.

**Comment by meyer9** [comment]
Agreed. Also, we might have something like this to ensure everything is linted/PEP-8 conformant: https://github.com/markstory/lint-review

**Comment by jtdroste** [comment]
Agreed on the squashes.  Will we also be squashing when merging?

**Comment by meyer9** [comment]
rebase for merging I think?

**Comment by MaxLeiter** [comment]
I think we should rebase for merging and have contributors do the squashing.

**Comment by jtdroste** [comment]
Added stuff about contributors doing squashing

**Comment by jtdroste** [comment]
GitHub team `@OpenPoGo/maintainers` added.  They will be tagged on every PR.

**Comment by jtdroste** [comment]
I'll take ownership of this issue to make sure it's completed

**Comment by MaxLeiter** [comment]
If someone could make a MAINTAINERS.md or wiki page with this information that'd be great

**Comment by Maximum-throwaway** [comment]
SGTM

**Comment by MaxLeiter** [comment]
:+1: from me

**Comment by wchill** [comment]
+1

**Comment by jmeyer2k** [comment]
+1 from me

**Comment by meyer9** [comment]
how can we keep track of the number of approvals?

**Comment by Reaver01** [comment]
Are we just typing approval?
what if I want to thumbs up the main post instead?
+1

**Comment by jtdroste** [comment]
@jmeyer2k If you're talking about approvals on a PR - we'll use [this](https://about.pullapprove.com/).

Either is fine @Reaver01

**Comment by brantje** [comment]
+1

**Comment by meyer9** [comment]
yeah, let's get that setup then.

**Comment by jtdroste** [comment]
> All work must be done via PR's - even if done by a maintainer
> All PRs must get two approvals/👍 from@OpenPoGo/maintainers before merging
> All PRs must pass CI
> One PR per feature
> All PR commits must be concise and squashed (done via the contributor)
> All PRs should be merged via rebase

Done.

> All PRs must pass pep8 standards (this will be checked automatically)

See: #4
