### ISSUE TITLE
Bot appears to loop after period of normal functionality

### ISSUE THREAD

**Issue by cypherlou** [OpenPoGo/OpenPoGoBot#313]
### Summary

After a period of expected results (generally just under 30 minutes) the Bot seems to enter a state where it is no longer interacting with the Niantic Labs servers properly. The Bot continues to navigate between PokeStops but fails to spin them and never sees any Pokemon whilst on its travels. There is no report of a soft ban.
### Limited analysis

When run in --debug mode the Bot seems to be in a loop, making a GET_MAP_OBJECTS request repeatedly. It declares that the session ticket is still valid `for further 00:33:38 hours`, makes the request after dumping the `Generated protobuf request` and then immediately goes back to the start of the process again, almost as if there is a silent failure somewhere.

`2016-08-15 09:15:30,962 [   rpc_api] [DEBUG] Execution of RPC`
`2016-08-15 09:15:30,964 [connectionpool] [ INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com`
`2016-08-15 09:15:31,114 [connectionpool] [DEBUG] "POST /plfe/262/rpc HTTP/1.1" 200 None`
### Next steps

I'm happy to have a look at the code but wanted to confirm this is unexpected behaviour, hasn't already been reported, etc.
### Other Information

OS: ubuntu 14.04
Git Commit: latest

**Comment by wchill** [comment]
That is a softban (possibly for your IP and not just the account), but our detection for the new softbans isn't up to scratch yet.

**Comment by cypherlou** [comment]
Thanks for the rapid response, really appreciated.
