### ISSUE TITLE
"location_cache" is read instead of "location" resulting in error

### ISSUE THREAD

**Issue by tkuenzle** [OpenPoGo/OpenPoGoBot#315]
### Expected Behavior

If no cached location is found, the value from 'location' should be read.
### Actual Behavior

Tries to read 'location_cache' as a string which results in the error

`File "pokemongo_bot/__init__.py", line 285, in _get_pos_by_name
    if location_name.count(',') == 1:
AttributeError: 'bool' object has no attribute 'count'`
### Sugested Solution

Change line 278 of "pokemongo_bot/**init**.py" to
`self.position = self._get_pos_by_name(self.config["mapping"]["location"])`
### Steps to Reproduce

Run the bot without cached location.
### Other Information

OS: OS X El Capitan
Git Commit: 039613290cd859cd88ee822b8da181b4aba5efd6

**Comment by torvitas** [comment]
same here, preparing pull request

**Comment by ajurna** [comment]
it's a simple enough fix. just change the key to location

**Comment by andythorne** [comment]
Fixed in #270
