### ISSUE TITLE
Level Up Rewards

### ISSUE THREAD

**Issue by PhilippHeuer** [OpenPoGo/OpenPoGoBot#319]
Niantic might be able to detect user's that didn't claim their rewards despite leveling up?
This could be a "bot account" indicator.
### Expected Behavior

Level up rewards are recieved using the bot.
### Actual Behavior

Level up rewards are only given when you log in for the first time after the level up on the smartphone app. (stacks if you don't login for a while)
I recieved 800+ Items at once after logging in for the first time on my level 20+ Account.
Bag Status: 1062/350
### Steps to Reproduce

Level the bot and login on the smartphone later.
### Other Information

OS: Ubuntu
Git Commit: 0396132
### Screenshot

![screenshot_2016-08-15-16-07-05](https://cloud.githubusercontent.com/assets/10275049/17668174/5a8eb72a-6308-11e6-868d-68443bc79505.png)

**Comment by niicojs** [comment]
Do you happen to know the api to do that?

**Comment by PhilippHeuer** [comment]
I will write a plugin to do that.

**Comment by meyer9** [comment]
I believe this happens even in the app. If you level up with a full backpack, it doesn't matter.

**Comment by plgonzalezrx8** [comment]
This is incorrect. You DO get the rewards when you level up using the bot, the behavior in app is just eye candy.

**Comment by xasdf** [comment]
@jmeyer2k it's not about overflowing the bag. It's that bot never claims the level-up reward. He logged his bot with official game client and received reward from lvl2, lvl3, lvl4, ..., lvl20+ all at once.
This definitely needs a fix as it is trivial for Niantic to flag such accounts.

**Comment by PhilippHeuer** [comment]
To clarify:
It's as xasdf interpreted it, you don't get any items if the bot levels up.
And if you start the app for the first time you get the rewards for all levels at once.

**Comment by PhilippHeuer** [comment]
A little update:

The plugin is done and the rewards are recieved.
But im still working on a "loot" display.

I'm also showing a "level up" notice in the chat on level up.

I'm going to create a pr as soon as it's done.

**Comment by niicojs** [comment]
don't forget to fire an event, like "player_level_update" or something like that.

**Comment by PhilippHeuer** [comment]
My Account got perma banned the next day. Maybe someone else wants to try this.

**Comment by andythorne** [comment]
Fixed in #331
