### ISSUE TITLE
Usage: pokecli.py [path to config.yml]

### ISSUE THREAD

**Issue by UnKn0wN-Binary-zz** [OpenPoGo/OpenPoGoBot#324]
### Expected Behavior

Bot Should Run after clean install 
### Actual Behavior

$ python pokecli.py -j
Command line arguments are deprecated. See README for details.
Usage: pokecli.py [path to config.yml]
### Steps to Reproduce

I do have a config.yml in my main directory and my configs directory, both do not work when trying to run the bot and I have filled out all necessary Fields. 
### Other Information

OS: Win7 
Git Commit:

**Comment by wchill** [comment]
Remove all command line switches if using the default config location.
