### ISSUE TITLE
Set-up troubleshooting

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [OpenPoGo/OpenPoGoBot#335]
Hi All, 

Please see screenshot I'm having trouble setting up my bot in my pc. Any help?

<img width="686" alt="screen shot 2016-08-17 at 10 36 15 am" src="https://cloud.githubusercontent.com/assets/5118009/17722691/ae7a8d96-6466-11e6-9f24-0bc3ccc806c3.png">

Thank you so much!

OS: Mac Yosemite

**Comment by rjjohnpatrickcruz** [comment]
I Manage to fix my concern here. newbie issue.. ;)
Thanks!

**Comment by MaxLeiter** [comment]
Mind sharing your fix for others, @rjjohnpatrickcruz ?
