### ISSUE TITLE
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [OpenPoGo/OpenPoGoBot#336]
### Expected Behavior

Can run the bot smoothly
### Actual Behavior

after configuring details when I run python command it says
pgoapi.exceptions.ServerSideAccessForbiddenException: Seems your IP Address is banned or something else went badly wrong...
### Steps to Reproduce

run 
- python pokecli.py config/config.yml
### Other Information

<img width="763" alt="screen shot 2016-08-17 at 11 27 38 am" src="https://cloud.githubusercontent.com/assets/5118009/17723577/a98c5aba-646d-11e6-8998-380500f6a643.png">

OS: OSX
Git Commit:

**Comment by wchill** [comment]
Your account is banned. This currently affects all bots and accounts utilized by mapping services. We are working to fix this, but until then there is nothing you can do except make a new account.

**Comment by wchill** [comment]
Sorry, wrong error. If you are running on a cloud service or VPS provider, Niantic has blacklisted those IPs. This also affects all other unofficial projects. Use a different IP.
