### ISSUE TITLE
Cant find encrypt.dll in Linux OS ????

### ISSUE THREAD

**Issue by bornbygoogle** [OpenPoGo/OpenPoGoBot#337]
### Expected Behavior

OSError: libencrypt.so: cannot open shared object file
### Actual Behavior

OSError: encrypt.dll: cannot open shared object file
### Steps to Reproduce

python pokecli.py config/config.yml
### Other Information

OS: Linux
Git Commit: lastest

**Comment by bornbygoogle** [comment]
Anyone else have same prob on Linux ? o.O

**Comment by wanderingconfused** [comment]
I am having the same issue. I used to be able to use the library flag to point to libencrypt.so, but I don't know if that is still an option in the yaml config.

**Comment by niicojs** [comment]
not on linux, but replacing `load_library: "encrypt.dll"` by `load_library: "libencrypt.so"` should do it.

**Comment by wanderingconfused** [comment]
Yeah just noticed that in the yaml file, I am blind sometimes I swear.
