### ISSUE TITLE
Automatic evolutions

### ISSUE THREAD

**Issue by meyer9** [OpenPoGo/OpenPoGoBot#34]
There should be a flag called --evolve-pokemon which enables automatic evolutions of Pokemon. 
When the flag is active, whenever the player acquires enough candy to evolve a pokemon, it should evolve the highest CP pokemon. This can also be paired with --initial-evolve which iterates over all of the of the current pokemon and evolves any that can be evolved. The default for these two arguments should be False.

**Comment by hshintaro** [comment]
I'd like to pokemon transfer list (viceversa ignor list)

**Comment by andythorne** [comment]
Closing as done in #194.
