### ISSUE TITLE
If evolve list is empty, it would not iterate

### ISSUE THREAD

**Issue by prophaner** [OpenPoGo/OpenPoGoBot#345]
### Expected Behavior

pokemon should evolve
### Actual Behavior

  File "./plugins\evolver__init__.py", line 31, in _do_evolve
    if base_name in evolve_list and evolve_list[base_name]["evolve"] is True:
TypeError: argument of type 'NoneType' is not iterable
### Steps to Reproduce

pokemon tries to evolve
### Other Information

OS: windows
Git Commit: most recent...

**Comment by wchill** [comment]
If you want an empty evolve list, replace the list with `[]`. So your config should only have `evolve_filter: []`
