### ISSUE TITLE
No such file or directory: 'config/p'

### ISSUE THREAD

**Issue by t-v** [OpenPoGo/OpenPoGoBot#352]
### Executed Command

$ python pokecli.py config/config.yml
### Expected Behavior

The bot to start and read all the config files
### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 88, in <module>
    main()
  File "pokecli.py", line 73, in main
    kernel.boot()
  File "/home/xxx/git/OpenPoGoBot/app/kernel.py", line 55, in boot
    self.load_config()
  File "/home/xxx/git/OpenPoGoBot/app/kernel.py", line 39, in load_config
    for node in os.listdir(os.path.join(config_dir, plugin_config_dir)):
OSError: [Errno 2] No such file or directory: 'config/p'
### Steps to Reproduce

Loading the most default config
### Other Information

OS: Fedora 24
Git Commit: 37560cfbc5fac78c26cc4e405746991792f96559

**Comment by niicojs** [comment]
Look at the config.yml example, it has changed quite a bit recently so you have to update yours to match the example.

**Comment by t-v** [comment]
@nicoschmitt I did check it, and it seems it doesn't do what the code expects. This is why I made a small pullrequest of it.
The main issue was in the plugins part:
`plugins:
    # Do not automatically load the specified plugins
    exclude: []

```
# Plugin directories to load
include:
    - ./plugins

# Load plugin YAML config files from this folder
config: "plugins"`
```

As you can see, the last part is a string instead of a list and in the code, it tries to iterate over that. To fix it in my config file, I put brackets around it. (see pullrequest)

**Comment by niicojs** [comment]
It should be:
config:
- plugins 

In your yml.

**Comment by niicojs** [comment]
config.yml.example is correct.
