### ISSUE TITLE
Automated bot testing with Travis

### ISSUE THREAD

**Issue by wchill** [OpenPoGo/OpenPoGoBot#39]
~~Currently Travis only runs `pep8` and exits. It might make sense for us to create one or more dummy accounts with various different input parameters and run the bot for a few minutes in the Travis build to make sure the bot at least has baseline functionality working.~~

~~This will most likely miss edge cases/unexpected behavior, but it'll give additional confirmation that the codebase will run successfully.~~

~~[Obviously login credentials should be encrypted](https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions), but this will not work for PRs from 3rd party forks (though it will work for branches in this repo). Even with this limitation, it might be worthwhile. Thoughts?~~

Cloud providers have been blocked from accessing Niantic's API, however unit testing and mocks can be used instead.

**Comment by joseph-abell** [comment]
As long as someone gives this enough time as a feature, I think it could be worthwhile.

**Comment by meyer9** [comment]
:+1: I think this can be done relatively quickly. Someone needs to write automated tests.

**Comment by wchill** [comment]
Blocked by #44.

**Comment by jtdroste** [comment]
Niantic is currently blocking AWS (as well as other cloud providers).  Thus, travis-ci.org builds will not be able to connect to the "live" servers.

I propose implementing mocking of the API response objects.  This is already underway with the `/api` module addition

**Comment by andythorne** [comment]
This is currently being worked on!

Edit: didn't read the title correctly - unit and functional tests are being worked on, rather than bot running as a test. As cloud providers are blocked this is the next best thing.

**Comment by wchill** [comment]
Edited description to reflect the cloud provider block situation.

**Comment by wchill** [comment]
Since we have tests running in Linux, OS X, and Windows (PRs #215, #248, #252, #261, #272) this should be good now.
