### ISSUE TITLE
Setup CI tests

### ISSUE THREAD

**Issue by MaxLeiter** [OpenPoGo/OpenPoGoBot#4]
All PRs should be tested for style/pep8/pylint via Jenkins or some other CI

**Comment by jtdroste** [comment]
Related: #3

**Comment by wchill** [comment]
I can set up the server, but someone will have to write tests

**Comment by jtdroste** [comment]
Owning this.  Setting up travis-ci.

TODO: learn about travis-ci.

**Comment by wchill** [comment]
I do know Travis CI well enough (as opposed to Jenkins) if you want to assign me to that.

**Comment by jtdroste** [comment]
Re-assigned to @wchill.  You're awesome!
