### ISSUE TITLE
Transition to only support Python 3.5

### ISSUE THREAD

**Issue by meyer9** [OpenPoGo/OpenPoGoBot#44]
Mostly for typing and being more organized. I think we need to eventually transition to only support python 3.5.

Please up/down vote this post for your decision.

**Comment by wchill** [comment]
Disagree; Python 2.7 is still common enough that I think it's worth supporting even at the cost of some readability.

(I use Python 2.7 myself primarily, so I'm not without bias, but if there is enough support for 3.5 only then I'm not against it.)

**Comment by douglascamata** [comment]
Project is new, so I think it's much better to switch the standard development to 3.5 and support 2.7 only through `six`.

**Comment by wchill** [comment]
There's a lot of work to be done since original code base is that bad. This should wait until after refactor.

**Comment by brantje** [comment]
Disagree, most of the module's i use for plugin(s) are python 2.7

**Comment by wchill** [comment]
For the foreseeable future, we will continue to support both.
