### ISSUE TITLE
Can't get web. 

### ISSUE THREAD

**Issue by Paramon** [OpenPoGo/OpenPoGoBot#48]
### Actual Behavior

cloning into 'web'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:OpenPoGo/OpenPoGoWeb.git' into submodule path 'web' failed
### Steps to Reproduce

 git submodule init
 git submodule update
### Other Information

OS: 
Git Commit:

**Comment by meyer9** [comment]
hmm that's weird. have you tried deleting the repo and trying git clone --recursive ...?

**Comment by MaxLeiter** [comment]
You're using the SSH URL not HTTP

**Comment by Paramon** [comment]
I see pip install it into env/src folder. We have hard coded path to web module. I suggest to isolate web module. To run without it if needed.

**Comment by JulianMBr** [comment]
@Paramon Hey, I guess the main issue is solved then. 
If you want, you can create another issue with your proposed idea to isolate the web module. That way we can address and track issues more efficiently.
