### ISSUE TITLE
Avoid walking on water

### ISSUE THREAD

**Issue by wchill** [OpenPoGo/OpenPoGoBot#50]
Currently the bot walks on water which can be problematic.

Ideally the bot should avoid waterways by using Google Maps directions API to navigate to the correct location.

**Comment by meyer9** [comment]
honestly this isn't a big deal. they can't just ban people from using it on a boat

**Comment by meyer9** [comment]
polywalker anyone?

**Comment by kazyka** [comment]
Do not know if it is implementet yet in pokomonGo-Bot's newest master, but the bot still walks on water

**Comment by Saturate** [comment]
I created the issue on the other bots repo: https://github.com/PokemonGoF/PokemonGo-Bot/issues/944

I think it would be nice, it's really walking super strange, the directions API would be a real nice improvement.
