### ISSUE TITLE
Bot's incorrect "walking"

### ISSUE THREAD

**Issue by sniok** [OpenPoGo/OpenPoGoBot#58]
### Expected Behavior

Bot walks smoothly 
### Actual Behavior

Bot moves too fast or teleports causing softban and crashes

PoGo bot (Not my screenshot but in my case it's the same as this)
![image](https://cloud.githubusercontent.com/assets/4517681/17099641/53fe3ee0-5272-11e6-8fbe-80d7d1a89881.png)

PokemonGoF Bot
![image](https://cloud.githubusercontent.com/assets/4517681/17099670/843784ea-5272-11e6-827b-db4315fc77ea.png)

Walk speed on both bots are 4
### Other Information

OS: Mac OS
Git Commit: 65f0fb86e3188511fc46a083786c8ab72c6bd076

**Comment by meyer9** [comment]
Fixed in #67
