### ISSUE TITLE
Bot does not write location-*username*.json to Web directory

### ISSUE THREAD

**Issue by corang** [OpenPoGo/OpenPoGoBot#64]
### Expected Behavior

location-_username_.json in web directory
### Actual Behavior

file not found which causes web page to not work
### Steps to Reproduce

start bot
start webserver
observe directory contents and webserver console
### Other Information

OS: Windows 10
Git Commit: Newest as of 12:25 AM EST July 26, 2016 (Master)

**Comment by corang** [comment]
There is a <s>fix</s> workaround. You need to manually create the json file with the correct name and {} as the file contents as referenced in this issue comment [https://github.com/OpenPoGo/OpenPoGoWeb/issues/50#issuecomment-235160302](url)

**Comment by meyer9** [comment]
so, it does create the file?

**Comment by corang** [comment]
It does not create the file but once the file is there it will write to it.

**Comment by meyer9** [comment]
I couldn't recreate this, but I don't have a windows computer atm to test.

**Comment by wchill** [comment]
This system will be replaced anyway, so using the workaround is encouraged.
