### ISSUE TITLE
Add option to disable plugins

### ISSUE THREAD

**Issue by meyer9** [OpenPoGo/OpenPoGoBot#78]
Add option to disable plugins like web, etc.

**Comment by MaxLeiter** [comment]
There are a few ways we can go about this, here are the options on the top of my head:
- commandline option (--<plugin_name>) and relevant config.json entry
- commandline option array (--plugins) and relevant config.json entry (not sure if this is possible or reasonable)
- any folder in the `plugins/` directory (currently)
- seperate plugins.json file (strongly against, but might make most sense)

**Comment by meyer9** [comment]
I think there should be an exclude plugin option since most plugins should be default.

**Comment by wchill** [comment]
Closed by #83.
