### ISSUE TITLE
toon not moving anymore on the map

### ISSUE THREAD

**Issue by MathieuVachon** [OpenPoGo/OpenPoGoBot#85]
As said in the subject, the toon is no longer moving while watching on the map.

**Comment by meyer9** [comment]
this needs to be fixed with sockets

**Comment by suchpool** [comment]
I second that, since last pull I made the web UI interface updated and it's not moving anymore. Sometimes even with refresh it will show a previous location where I launched the bot rather than where it is currently.

**Comment by MathieuVachon** [comment]
thx for the fix.
