### ISSUE TITLE
[bug] Location Cache Not Used | config.json -> location_cache: true

### ISSUE THREAD

**Issue by RedSparr0w** [OpenPoGo/OpenPoGoBot#88]
### Expected Behavior

Bot starts from last recorded location specified in `data/last-location-{username}.json`
### Actual Behavior

Bot starts at specified location from config,json
### Steps to Reproduce
- Run bot with config.json settings:

``` json
"location": "123 Sesame Street",
"location_cache": true,
```
- wait for bot to move away from location
- restart bot
### Other Information

OS: Windows 10
Git Commit: [newest | master | @ 4:20pm (GMT+12)](https://github.com/OpenPoGo/OpenPoGoBot/tree/f6af4cbd6adb3aa37365f0a04e9e7f5302182347)

**Comment by JulianMBr** [comment]
This bug will be fixed with the PR #89 from @epicblood.

Thanks for reporting @RedSparr0w !

**Comment by RedSparr0w** [comment]
This issue seems to still be happening for me with latest [master commit](https://github.com/OpenPoGo/OpenPoGoBot/tree/0fa223b6143d1d82790b0d1e511fad5928749bc7),

if i launch with `-lc` flag it will load the location cache as expected
but with only using `--config-json config.json` it ignores the option in `config.json` file.

config:

``` json
{
    "auth_service": "google",
    "username": "OpenPoGoBot@gmail.com",
    "password": "OpenPoGo",
    "location": "-12.34567,123.4567",
    "cp": 100,
    "max_steps": 50,
    "mode": "all",
    "walk": 4.16,
    "initial_transfer": true,
    "recycle_items": true,
    "pokemon_potential": 0.70,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": {
        "1": { "keep": 50 },
        "101": { "keep": 10 },
        "102": { "keep": 30 },
        "103": { "keep": 30 },
        "201": { "keep": 30 },
        "701": { "keep": 100 }
    }
}
```

edit: clarify more information

**Comment by MaxLeiter** [comment]
I think this is intended; the commandline overrides the JSON. if `-lc` is enabled, then `--location` should be ignored (in case, for example, someone adds `-lc` last minute and doesn't want to remove the `--location` line for the future)

**Comment by RedSparr0w** [comment]
But if i have no command line functions (no -lc and no --location) only `--config-json config.json` it ignores if the config.json -> location_cache is set to true

**Comment by MaxLeiter** [comment]
That's expected, -lc should override --location
