### ISSUE TITLE
Feature: Give list of locations

### ISSUE THREAD

**Issue by dbmurphy** [OpenPoGo/OpenPoGoBot#92]
### Expected Behavior

Currently the bot will walk to random locations in a given range, it could be  great to provided an ordered list/dict or locations you want to visit.

--location "53.3468069,-6.2589212"  --destionations=destionations.js

destionations.js

```
destionations = [ 
"53.3457565,-6.2604233"
"53.3448982,-6.2632986"
"53.3442321,-6.2640496"
"53.3430407,-6.2645432"
"53.3444627,-6.2595864"
"53.3444243,-6.2530418"
"53.3422721,-6.2534495"
"53.3434507,-6.2594899"
]
```

This would let people map out their favorite locations within a locale to have the bot visit.

I am looking at writing a Pokemon history system that could then scan the areas for  Pokemon noticed ( similar to pokevision.com but with history).  Over time this would also let the bot be able to have time-based logic such as be @ gps X at 12:20-12:34 to try and get a spawn. Obviously this could use more refinement but initially just being able to have a walk list in the bot would be great.

**Comment by kazyka** [comment]
Maybe also give the bot a maximum range from the beginning point that it can move? So i.e. set it to 500m and then the bot stays within this range. This could be used to farm a spot where one type of pokemon spawns?

**Comment by dbmurphy** [comment]
@kazyka Doesn't max_steps already give you this to a reasonable level? Or do you need something different? My thought was more a playlist of cord to go to allowing you to define a walk / transit path you want to follow. I think it might need to allow a small amount of jitter but it would only be by a slot or two. I found using max_steps I could keep the bot walking in a pretty tight area to get the spawns I wanted in a single location.

**Comment by kazyka** [comment]
@dbmurphy I think it does. But max_steps should be changed to max_distance_in_meters, this is more logical, than max_steps, the user do not know a long a step is. But this is a different idea, than your pathing idea. Sorry I hijacked your thread

**Comment by ch333** [comment]
A list or at least a path appears to be implemented in the original PoGo-Bot, which this project forked off from.

**Comment by andythorne** [comment]
This feature is coming with #127!
