### ISSUE TITLE
Egg Hatching

### ISSUE THREAD

**Issue by dbmurphy** [OpenPoGo/OpenPoGoBot#97]
### Suggested improvement

RPC understands about incubators as such  we  could do two things:

1) SeenFortWorker, could check if any eggs have hatched
2) WalkTowardsFortWorker can add an egg to an empty incubator and then this class would let it mature.

This will allow better use of eggs, and the ability to get more rare Pokemon we normally would miss out on in the bot system.

**Comment by kazyka** [comment]
Would be a nice feature, but is it possible to only use the infinity egg hatcher?

**Comment by dbmurphy** [comment]
Yeah, that should be pretty each to match the name of the item when selecting  the incubator.

**Comment by ch333** [comment]
This feature appears to be implemented in the original PoGo-Bot, which this project forked off from.

**Comment by dbmurphy** [comment]
Correct it's a recent addition that needs to be ported. I started working on that and some tweaking but have not finished due to looking at other more pressing things.
